theme = "brogrammer"

[editor]
scrolloff = 4
line-number = "relative"
cursorline = true
rulers = [100]
color-modes = true
bufferline = "multiple"
auto-save = true
idle-timeout = 0

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["diagnostics", "selections", "position", "position-percentage", "version-control", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# Better moving around
g = { k = ["goto_file_start"], j = ["goto_file_end", "goto_first_nonwhitespace"], h = ["goto_first_nonwhitespace"] }
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

[keys.select]
g = { k = ["goto_file_start"], j = ["goto_file_end", "goto_first_nonwhitespace"], h = ["goto_first_nonwhitespace"] }
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
