#!/bin/bash

#    __________  _____
#   / ____/ __ \/ ___/
#  / / __/ / / /\__ \  Gabriel Dos Santos
# / /_/ / /_/ /___/ /  https://github/dssgabriel
# \____/_____//____/
#
# My startup script for leftwm.

# Export the script path
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
    compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
    picom &> /dev/null &
fi

# Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Set wallpaper
if [ -x "$(command -v feh)" ]; then
    feh --bg-fill $SCRIPTPATH/background.jpg
fi

# Boot polybar
index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
    barname="mainbar"
    monitor=$monitor offsetx=$x width=$width polybar -c .config/polybar/config.ini $barname &> /dev/null &
    let index=index+1
done

# Boot notification manager
dunst &
