#! /bin/sh
#    __________  _____
#   / ____/ __ \/ ___/
#  / / __/ / / /\__ \  Gabriel Dos Santos
# / /_/ / /_/ /___/ /  https://github/dssgabriel
# \____/_____//____/                
# 
# My configuration for bspwm, the binary space partitioning window manager.

# bspc rule -r "*"
sxhkd &

# Monitors
bspc monitor -d 一 二 三 四 五 六 七
# #bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# bspwm config
bspc config border_width 			0
bspc config border_radius 			16
bspc config window_gap          	24
bspc config top_padding				32
bspc config split_ratio          	0.50
bspc config borderless_monocle    	true
bspc config gapless_monocle       	false
bspc config focus_follows_pointer 	true
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_corner

bspc config normal_border_color 	"#222222"
bspc config focused_border_color 	"#191919"

# Other
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

$HOME/scripts/startup.sh
