#! /bin/sh
#    __________  _____
#   / ____/ __ \/ ___/
#  / / __/ / / /\__ \  Gabriel Dos Santos
# / /_/ / /_/ /___/ /  https://github/dssgabriel
# \____/_____//____/
#
# My configuration for bspwm, the binary space partitioning window manager.

bspc rule -r "*"
# Start sxhkd
sxhkd &
# Start polybar
polybar.sh &

# Monitors settings
if xrandr -q | rg "HDMI1 connected"; then
    bspc monitor HDMI1 -d brave term more docs discord
fi
bspc monitor eDP1 -d brave term more docs discord

# Global settings
bspc config automatic_scheme            alternate
bspc config initial_polarity            second_child
bspc config click_to_focus              none
bspc config focus_follows_pointer 	    true
bspc config pointer_modifier            super
bspc config pointer_action1 		    move
bspc config pointer_action2 		    resize_corner
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# Window settings
bspc config padding				8
bspc config window_gap          8
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.50

# Border settings
bspc config border_width 			2
bspc config normal_border_color 	"#262221"
bspc config focused_border_color 	"#ab9382"

# Others
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Eog state=fullscreen
